config/routes.rb
Rails.application.routes.draw do
  
  # sign out path
  devise_scope :member do
    get '/members/sign_out' => 'devise/sessions#destroy'
  end

  
  devise_for :members
  resources :tutors 

  get 'home/about'
  root 'home#index' # this is the home page route (i.e. localhost:3000)

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many  :tutors
end

app/models/tutor.rb
class Tutor < ApplicationRecord
  belongs_to :member
end

app/models/tutors_test.rb
require "application_system_test_case"

class TutorsTest < ApplicationSystemTestCase
  setup do
    @tutor = tutors(:one)
  end

  test "visiting the index" do
    visit tutors_url
    assert_selector "h1", text: "tutors"
  end

  test "should create tutor" do
    visit tutors_url
    click_on "New tutor"

    fill_in "Email", with: @tutor.email
    fill_in "First name", with: @tutor.first_name
    fill_in "Last name", with: @tutor.last_name
    fill_in "Phone", with: @tutor.phone
    fill_in "Birthday date", with: @tutor.birthday_date
    fill_in "School name", with: @tutor.school_name
  
    click_on "Create tutor"

    assert_text "tutor was successfully created"
    click_on "Back"
  end

  test "should update tutor" do
    visit tutor_url(@tutor)
    click_on "Edit this tutor", match: :first

    fill_in "Email", with: @tutor.email
    fill_in "First name", with: @tutor.first_name
    fill_in "Last name", with: @tutor.last_name
    fill_in "Phone", with: @tutor.phone
    fill_in "Birthday date", with: @tutor.birthday_date
    fill_in "School name", with: @tutor.school_name
    click_on "Update tutor"

    assert_text "tutor was successfully updated"
    click_on "Back"
  end

  test "should destroy tutor" do
    visit tutor_url(@tutor)
    click_on "Destroy this tutor", match: :first

    assert_text "tutor was successfully destroyed"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  
  def index
  end

  def about
    @about_me = <<-ABOUT_ME
      Hi there! My name is Yifan, and I am a full-stack development student at Red River 
      College Polytechnic in Winnipeg, MB. This is my first Ruby on Rails application.
     I hope you like it!Feel free to email(yifanlicode@gmail.com) me.
    ABOUT_ME

  end
  
end

app/controllers/tutors_controller.rb
class TutorsController < ApplicationController
  before_action :set_tutor, only: %i[ show edit update destroy ]
  before_action :authenticate_member!, except: [:index, :show]
  before_action :correct_member, only: [:edit, :update, :destroy]


  # GET /tutors or /tutors.json
  def index
    @tutors = current_member.tutors
  end

  # GET /tutors/1 or /tutors/1.json
  def show
  end

  # GET /tutors/new
  def new
    @tutor = current_member.tutors.build
  end

  # GET /tutors/1/edit
  def edit
  end

  # POST /tutors or /tutors.json
  def create
    @tutor = current_member.tutors.build(tutor_params)

    respond_to do |format|
      if @tutor.save
        format.html { redirect_to @tutor, notice: 'tutor was successfully created.' }
        format.json { render :show, status: :created, location: @tutor }
      else
        format.html { render :new }
        format.json { render json: @tutor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tutors/1 or /tutors/1.json
  def update
    respond_to do |format|
      if @tutor.update(tutor_params)
        format.html { redirect_to tutor_url(@tutor), notice: "tutor was successfully updated." }
        format.json { render :show, status: :ok, location: @tutor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tutor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tutors/1 or /tutors/1.json
  def destroy
    @tutor.destroy
    respond_to do |format|
      format.html { redirect_to tutors_url, notice: "tutor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_member
    @tutor = current_member.tutors.find_by(id: params[:id])
    redirect_to tutors_path, notice: "Not Authorized To Edit This tutor" if @tutor.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tutor
      @tutor = Tutor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tutor_params
      params.require(:tutor).permit(:first_name, :last_name, :email, :phone, :birthday_date,:school_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tutors_helper.rb
module TutorsHelper
end

app/views/home/_footer.html.erb
<footer class="bg-light py-3 footer fixed-bottom">
  <div class="container">
    <div class="row">
      <div class="col-lg-4">
        <p class="mb-0 text-center text-lg-start">© 2023 Tutors App</p>
      </div>
      <div class="col-lg-4">
        <h5 class="mb-3 text-center">Subscribe to Our Newsletter</h5>
        <form class="subscribe-form d-flex flex-row">
          <div class="form-group">
            <label for="email" class="visually-hidden">Email address</label>
            <input type="email" class="form-control me-2" id="email" placeholder="Enter your email address">
          </div>
          <button type="submit" class="btn btn-primary">Subscribe</button>
        </form>
      </div>
      <div class="col-lg-4">
        <h5 class="mb-3 text-center">Follow Us</h5>
        <ul class="list-unstyled d-flex justify-content-center">
          <li class="me-4">
            <a href="https://twitter.com/yifanlicode" target="_blank">
            <i class="fab fa-twitter fa-2x"></i>
            </a>
          </li>

          <li class="me-4">
            <a href="https://github.com/yifanlicode" target="_blank">
             <i class="fab fa-github fa-2x"></i>
            </a>
          </li>

          <li class="me-4">
            <a href="https://discord.com/yifanli" target="_blank">
            <i class="fab fa-discord fa-2x"></i>
            </a>
          </li>

          <li class="me-4">
            <a href="https://reddit.com/" target="_blank">
            <i class="fab fa-reddit fa-2x"></i>
            </a>
          </li>

        </ul>
      </div>
    </div>
  </div>
</footer>
<!-- End of Footer -->

app/views/home/_header.html.erb
<nav class="navbar bg-primary navbar-expand-lg bg-body-tertiary" 
  data-bs-theme="dark">
  <div class="container-fluid">
  <%= link_to 'Tutors Book', root_path, class: "navbar-brand" %>

  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
      
    <% if member_signed_in? %>
      <li class="nav-item ms-lg-2">
      <%= link_to "Add Tutor", new_tutor_path, class: "nav-link #{'active' if controller_name == 'tutors' && action_name == 'new'}" %>
      </li>


      <li class="nav-item ms-lg-2">
        <%= link_to "Tutor List", tutors_path, 
        class: "nav-link #{'active' if controller_name == 'tutors' && action_name == 'index'}" %>
      </li>    

      <li class="nav-item ms-lg-2">
           <%= link_to "About Us",
          home_about_path,class:"nav-link #{'active' if controller_name == 'home' && action_name == 'about'}"
          %>
      </li>
      <form class="d-flex ms-lg-3" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    
       <li class="nav-item ms-lg-2 ">
        <%= link_to "Edit Profile",edit_member_registration_path,
        class:"nav-link #{'active' if controller_name == 'registrations' && action_name == 'edit'}"
            %>
        </li>
        
       <li class="nav-item ms-lg-2 ">
        <%= link_to "Log Out", destroy_member_session_path,
         data: { turbo: false }, method: :delete, class: "nav-link" %>
        </li>
      <% else %>

      <li class="nav-item">
           <%= link_to "About Us",
          home_about_path,class:"nav-link #{'active' if controller_name == 'home' && action_name == 'about'}"
          %>
      </li>
          <li class="nav-item ms-lg-2">
      <%= link_to "Sign Up",
      new_member_registration_path,class:"nav-link #{'active' if controller_name == 'registrations' && action_name == 'new'}"
          %>
      </li>
          <li class="nav-item ms-lg-2">
      <%= link_to "Log In ",
      new_member_session_path,class:"nav-link #{'active' if controller_name == 'sessions' && action_name == 'new'}"
          %>
      </li>
      <% end %>
        

      

    

    </ul>
  
  </div>
</div>
</nav>
<br>

app/views/home/about.html.erb
<!-- app/views/home/about.html.erb -->

<div class="container min-vh-100">
 

  <div class="about-content">   
    <h3>Tutor App</h3>
    <p>Tutors Book is a Ruby on Rails web application that provides a convenient platform for managing and contacting tutors' information.
  </p>
  </div>

  
  <div class="about-content">  
    <h3>Features</h3>
    <ul>
      <li>Register, Login/Logout, and edit user information</li>
      <li>Tutor Information Management:Create, read, update, and delete tutor information.</li>
      <li>User-Friendly Interface: The application will have an intuitive and responsive member interface design to provide an excellent member experience.
  </li>

    </ul>
  </div>


   <div class="about-content">

    <h3>Learn from the project</h3>
    <ol>
      <li>MVC Organization</li>
      <li>CRUD Scaffold</li>
      <li>Style Devise Views</li>
      <li>Database Association</li>
      <li>Fun with Controllers</li>
      <li>Git, Github, and Heroku</li>
    </ol>
  </div>


   <div class="about-content">
    <h3>About Me</h3>
    <p><%= @about_me %></p>

  </div>


 </div>

app/views/home/index.html.erb
<div class="container">
    <div class="row">
      <div class="col-md-6 offset-md-3 mt-5">
        <div class="content">
          <h1 class="text-center mb-4">Tutors Book</h1>
          <p class="text-center">Connect and stay in touch with all your tutors throughout your life. Easily store their
            information, send emails, and celebrate birthdays and holidays. Maintain a lifelong connection with those who
            have guided and supported you.</p>
          <p class="text-center">Browse through the list of tutors and explore their details. Stay connected and express
            your gratitude with ease.</p>
          <p class="text-center note">Note: This application is under development, with more features coming soon.</p>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta name="description" content="Tutor App is a platform to help users store the Tutor Info.">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" >


    <title>Tutors Book</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>


<body>
    <%# Header %>
    <%# Nav bar %>

    <%= render 'home/header' %>

    <div class="container">
    <% if notice %>
      <%= render 'layouts/alert' %>
    <% end %>
    <%= yield %>

    </div>

    <div class="main-content">
    </div>


    <!-- JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
 
   <%= render 'home/footer' %>

 
  </body>


</html>

app/views/tutors/_form.html.erb
<%= form_with(model: tutor, class: "my-4") do |form| %>
  <% if tutor.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(tutor.errors.count, "error") %> prohibited this tutor from being saved:</h2>

      <ul>
        <% tutor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<%# show the form %>
  <div class="mb-3">
    <%= form.text_field :first_name, class: "form-control placeholder-gray",
        placeholder:"First Name" %>
  </div>

  <div class="mb-3">
    <%= form.text_field :last_name, class: "form-control placeholder-gray ",
    placeholder:"Last Name" %>
  </div>

  <div class="mb-3">
    <%= form.text_field :email, class: "form-control placeholder-gray",
    placeholder:"Email" %>
  </div>

  <div class="mb-3">
    <%= form.text_field :phone, class: "form-control placeholder-gray",
    placeholder:"Phone Number" %>
  </div>

  <div class="mb-3">
    <%= form.text_field :school_name, class: "form-control placeholder-gray",
    placeholder:"School Name" %>
  </div>
  
 

  <div class="mb-3">
  <%= form.date_field :birthday_date, class: "form-control", 
    input_html: { class: "custom-date-field" } %>
</div>

 <div class="mb-3">
  <small class="text-muted"> * Please enter tutor's birthday date</small>
  <%= form.number_field :member_id,
    id: :tutor_member_id, class: "form-control", value: current_member.id, type: :hidden %>
</div>



 <div class="my-3">
  <div class="row justify-content-center">
  <div class="col-auto">
      <%= link_to "Back to tutors",
          tutors_path,
          class: "btn btn-secondary" %>
    </div>
    <div class="col-auto">
         <%= form.submit "Update this tutor", 
         class: "btn btn-primary" %>

    </div>
    <div class="col-auto">
        <%= link_to 'Delete this tutor', @tutor, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-dark" %>

    </div>
  </div>
</div>

<% end %>

app/views/tutors/_tutor.html.erb
<div id="<%= dom_id tutor %>" class="card">
  <div class="card-header bg-secondary text-white">
    <h1 class="card-title">
      <%= tutor.first_name %> <%= tutor.last_name %>
    </h1>
  </div>
  <div class="card-body">
    <p class="card-text">
      <strong>Email:</strong> <%= tutor.email %>
    </p>
    <p class="card-text">
      <strong>Phone:</strong> <%= tutor.phone %>
    </p>
    <p class="card-text">
      <strong>School Name:</strong> <%= tutor.school_name %>
    </p>
  </div>
  
</div>

app/views/tutors/edit.html.erb
<h1>Editing tutor</h1>

<%= render "form", tutor: @tutor %>

app/views/tutors/index.html.erb
<%# if member is signed in, show the tutors list %>

<% if member_signed_in? %> 
    <table class="table table-hover table-striped table-bordered">
    <thead class="table-dark">
        <tr>
        <th> Name </th>
        <th> Email </th>
        <th> Phone </th>
        <th> School </th>
        <th> Birthday </th>
        <th></th>
        </tr>
    </thead>

        <tbody>
        <% @tutors.each do |tutor| %>
                <% if tutor.member == current_member %>

                <tr>

                <%# show %>
                <td>
                    <%= link_to tutor.first_name + ' ' + tutor.last_name, tutor %>
                   </td>

                <td><%= tutor.email %></td>
                <td><%= tutor.phone %></td>
                <td><%= tutor.school_name %></td>
                <td><%= tutor.birthday_date%></td>

            
                <td>
                    <%= button_to 'Delete', 
                    tutor, 
                    method: :delete, 
                    data: { confirm: 'Are you sure?' }, 
                    class: "btn btn-outline-danger btn-sm" %>
                </td>
                <% end %>   
                </tr>    
        <% end %>

        </tbody>
    </table>

    <br>

    <%= link_to "New tutor", 
        new_tutor_path,
        class:"btn btn-primary" %>

    <br>
    <br>
    
<% end %>

app/views/tutors/new.html.erb
<h1>Add New tutor</h1>

<%= render "form", tutor: @tutor %>

app/views/tutors/show.html.erb
<%= render @tutor %>

 <div class="my-3">
  <div class="row justify-content-center">
  <div class="col-auto">
      <%= link_to "Back to tutors",
          tutors_path,
          class: "btn btn-secondary" %>
    </div>
    <div class="col-auto">
      <%= link_to "Edit this tutor",
          edit_tutor_path(@tutor),
          class: "btn btn-primary" %>
    </div>
    <div class="col-auto">
      <%= button_to "Delete this tutor",
          @tutor,
          class: "btn btn-dark",
          method: :delete,
          data: { confirm: "Are you sure?" } %>
    </div>
  </div>
</div>


<%# Path: app/views/tutors/_tutor.html.erb %>